namespace IwanaProxy.Services;

public static class Loc
{
    public static string Get(string key)
    {
        var lang = AppSettings.Instance.Language;
        if (Strings.TryGetValue((lang, key), out var val)) return val;
        if (Strings.TryGetValue((AppLanguage.English, key), out val)) return val;
        return key;
    }

    private static readonly Dictionary<(AppLanguage, string), string> Strings = new()
    {
        // English
        { (AppLanguage.English, "app_title"), "Iwana Proxy" },
        { (AppLanguage.English, "system_ready"), "SYSTEM READY" },
        { (AppLanguage.English, "loading"), "Fetching proxy list..." },
        { (AppLanguage.English, "testing"), "Testing {0} proxies..." },
        { (AppLanguage.English, "alive_count"), "{0} online" },
        { (AppLanguage.English, "no_proxies"), "No proxies found" },
        { (AppLanguage.English, "error_fetch"), "Error fetching proxies" },
        { (AppLanguage.English, "last_updated"), "Last updated: {0}" },
        { (AppLanguage.English, "search_placeholder"), "Search server or port..." },
        { (AppLanguage.English, "refresh"), "↻ Refresh" },
        { (AppLanguage.English, "connect"), "Connect" },
        { (AppLanguage.English, "scan_proxies"), "⚡  SCAN PROXIES" },
        { (AppLanguage.English, "online"), "ONLINE" },
        { (AppLanguage.English, "offline"), "OFFLINE" },
        { (AppLanguage.English, "testing_status"), "TESTING" },
        { (AppLanguage.English, "latency"), "LATENCY" },
        { (AppLanguage.English, "proxy"), "Proxy" },
        { (AppLanguage.English, "settings_title"), "Settings" },
        { (AppLanguage.English, "theme"), "Theme" },
        { (AppLanguage.English, "dark_mode"), "Dark" },
        { (AppLanguage.English, "light_mode"), "Light" },
        { (AppLanguage.English, "language"), "Language" },
        { (AppLanguage.English, "telegram_channel"), "Telegram Channel" },
        { (AppLanguage.English, "follow_us"), "Follow us on Telegram" },
        { (AppLanguage.English, "copy"), "Copy" },
        { (AppLanguage.English, "copied"), "Copied!" },
        { (AppLanguage.English, "save"), "Save" },
        { (AppLanguage.English, "telegram_error"), "Could not open Telegram. Please make sure Telegram Desktop is installed.\n\n" },
        { (AppLanguage.English, "error_title"), "Connection Error" },
        { (AppLanguage.English, "error_app"), "Application Error" },
        { (AppLanguage.English, "all_proxies"), "All proxies are created by third parties — we only collect them." },

        // Persian
        { (AppLanguage.Persian, "app_title"), "Iwana Proxy" },
        { (AppLanguage.Persian, "system_ready"), "سیستم آماده" },
        { (AppLanguage.Persian, "loading"), "در حال دریافت لیست پروکسی‌ها..." },
        { (AppLanguage.Persian, "testing"), "در حال تست {0} پروکسی..." },
        { (AppLanguage.Persian, "alive_count"), "{0} پروکسی فعال" },
        { (AppLanguage.Persian, "no_proxies"), "هیچ پروکسی‌ای پیدا نشد" },
        { (AppLanguage.Persian, "error_fetch"), "خطا در دریافت لیست پروکسی‌ها" },
        { (AppLanguage.Persian, "last_updated"), "آخرین بروزرسانی: {0}" },
        { (AppLanguage.Persian, "search_placeholder"), "جستجوی سرور یا پورت..." },
        { (AppLanguage.Persian, "refresh"), "↻ بروزرسانی" },
        { (AppLanguage.Persian, "connect"), "اتصال" },
        { (AppLanguage.Persian, "scan_proxies"), "⚡  اسکن پروکسی‌ها" },
        { (AppLanguage.Persian, "online"), "آنلاین" },
        { (AppLanguage.Persian, "offline"), "آفلاین" },

        { (AppLanguage.Persian, "testing_status"), "در حال تست" },
        { (AppLanguage.Persian, "latency"), "تاخیر" },
        { (AppLanguage.Persian, "proxy"), "پروکسی" },
        { (AppLanguage.Persian, "settings_title"), "تنظیمات" },
        { (AppLanguage.Persian, "theme"), "تم" },
        { (AppLanguage.Persian, "dark_mode"), "تاریک" },
        { (AppLanguage.Persian, "light_mode"), "روشن" },
        { (AppLanguage.Persian, "language"), "زبان" },
        { (AppLanguage.Persian, "telegram_channel"), "کانال تلگرام" },
        { (AppLanguage.Persian, "follow_us"), "ما را در تلگرام دنبال کنید" },
        { (AppLanguage.Persian, "copy"), "کپی" },
        { (AppLanguage.Persian, "copied"), "کپی شد!" },
        { (AppLanguage.Persian, "save"), "ذخیره" },
        { (AppLanguage.Persian, "telegram_error"), "باز کردن تلگرام ممکن نشد. مطمئن شوید Telegram Desktop نصب است.\n\n" },
        { (AppLanguage.Persian, "error_title"), "خطا در اتصال" },
        { (AppLanguage.Persian, "error_app"), "خطای برنامه" },
        { (AppLanguage.Persian, "all_proxies"), "تمام پروکسی‌ها توسط اشخاص ثالث ایجاد شده‌اند و ما فقط آن‌ها را جمع‌آوری می‌کنیم." },

        // Russian
        { (AppLanguage.Russian, "app_title"), "Iwana Proxy" },
        { (AppLanguage.Russian, "system_ready"), "СИСТЕМА ГОТОВА" },
        { (AppLanguage.Russian, "loading"), "Загрузка списка прокси..." },
        { (AppLanguage.Russian, "testing"), "Проверка {0} прокси..." },
        { (AppLanguage.Russian, "alive_count"), "{0} онлайн" },
        { (AppLanguage.Russian, "no_proxies"), "Прокси не найдены" },
        { (AppLanguage.Russian, "error_fetch"), "Ошибка загрузки прокси" },
        { (AppLanguage.Russian, "last_updated"), "Обновлено: {0}" },
        { (AppLanguage.Russian, "search_placeholder"), "Поиск сервера или порта..." },
        { (AppLanguage.Russian, "refresh"), "↻ Обновить" },
        { (AppLanguage.Russian, "connect"), "Подключить" },
        { (AppLanguage.Russian, "scan_proxies"), "⚡  СКАНИРОВАТЬ" },
        { (AppLanguage.Russian, "online"), "Онлайн" },
        { (AppLanguage.Russian, "offline"), "Оффлайн" },
        { (AppLanguage.Russian, "testing_status"), "ТЕСТ" },
        { (AppLanguage.Russian, "latency"), "ЗАДЕРЖКА" },
        { (AppLanguage.Russian, "proxy"), "Прокси" },
        { (AppLanguage.Russian, "settings_title"), "Настройки" },
        { (AppLanguage.Russian, "theme"), "Тема" },
        { (AppLanguage.Russian, "dark_mode"), "Тёмная" },
        { (AppLanguage.Russian, "light_mode"), "Светлая" },
        { (AppLanguage.Russian, "language"), "Язык" },
        { (AppLanguage.Russian, "telegram_channel"), "Telegram канал" },
        { (AppLanguage.Russian, "follow_us"), "Подпишитесь на нас в Telegram" },
        { (AppLanguage.Russian, "copy"), "Копировать" },
        { (AppLanguage.Russian, "copied"), "Скопировано!" },
        { (AppLanguage.Russian, "save"), "Сохранить" },
        { (AppLanguage.Russian, "telegram_error"), "Не удалось открыть Telegram. Убедитесь, что Telegram Desktop установлен.\n\n" },
        { (AppLanguage.Russian, "error_title"), "Ошибка подключения" },
        { (AppLanguage.Russian, "error_app"), "Ошибка приложения" },
        { (AppLanguage.Russian, "all_proxies"), "Все прокси созданы третьими лицами — мы только их собираем." },

        // Chinese
        { (AppLanguage.Chinese, "app_title"), "Iwana 代理" },
        { (AppLanguage.Chinese, "system_ready"), "系统就绪" },
        { (AppLanguage.Chinese, "loading"), "正在获取代理列表..." },
        { (AppLanguage.Chinese, "testing"), "正在测试 {0} 个代理..." },
        { (AppLanguage.Chinese, "alive_count"), "{0} 个在线" },
        { (AppLanguage.Chinese, "no_proxies"), "未找到代理" },
        { (AppLanguage.Chinese, "error_fetch"), "获取代理时出错" },
        { (AppLanguage.Chinese, "last_updated"), "最后更新: {0}" },
        { (AppLanguage.Chinese, "search_placeholder"), "搜索服务器或端口..." },
        { (AppLanguage.Chinese, "refresh"), "↻ 刷新" },
        { (AppLanguage.Chinese, "connect"), "连接" },
        { (AppLanguage.Chinese, "scan_proxies"), "⚡  扫描代理" },
        { (AppLanguage.Chinese, "online"), "在线" },
        { (AppLanguage.Chinese, "offline"), "离线" },
        { (AppLanguage.Chinese, "testing_status"), "测试中" },
        { (AppLanguage.Chinese, "latency"), "延迟" },
        { (AppLanguage.Chinese, "proxy"), "代理" },
        { (AppLanguage.Chinese, "settings_title"), "设置" },
        { (AppLanguage.Chinese, "theme"), "主题" },
        { (AppLanguage.Chinese, "dark_mode"), "深色" },
        { (AppLanguage.Chinese, "light_mode"), "浅色" },
        { (AppLanguage.Chinese, "language"), "语言" },
        { (AppLanguage.Chinese, "telegram_channel"), "Telegram 频道" },
        { (AppLanguage.Chinese, "follow_us"), "在 Telegram 上关注我们" },
        { (AppLanguage.Chinese, "copy"), "复制" },
        { (AppLanguage.Chinese, "copied"), "已复制!" },
        { (AppLanguage.Chinese, "save"), "保存" },
        { (AppLanguage.Chinese, "telegram_error"), "无法打开 Telegram，请确保已安装 Telegram Desktop。\n\n" },
        { (AppLanguage.Chinese, "error_title"), "连接错误" },
        { (AppLanguage.Chinese, "error_app"), "应用错误" },
        { (AppLanguage.Chinese, "all_proxies"), "所有代理均由第三方创建——我们只是收集它们。" },

        // Hindi
        { (AppLanguage.Hindi, "app_title"), "Iwana प्रॉक्सी" },
        { (AppLanguage.Hindi, "system_ready"), "सिस्टम तैयार" },
        { (AppLanguage.Hindi, "loading"), "प्रॉक्सी सूची लोड हो रही है..." },
        { (AppLanguage.Hindi, "testing"), "{0} प्रॉक्सी परीक्षण हो रहा है..." },
        { (AppLanguage.Hindi, "alive_count"), "{0} ऑनलाइन" },
        { (AppLanguage.Hindi, "no_proxies"), "कोई प्रॉक्सी नहीं मिली" },
        { (AppLanguage.Hindi, "error_fetch"), "प्रॉक्सी लाने में त्रुटि" },
        { (AppLanguage.Hindi, "last_updated"), "अंतिम अपडेट: {0}" },
        { (AppLanguage.Hindi, "search_placeholder"), "सर्वर या पोर्ट खोजें..." },
        { (AppLanguage.Hindi, "refresh"), "↻ रीफ्रेश" },
        { (AppLanguage.Hindi, "connect"), "कनेक्ट" },
        { (AppLanguage.Hindi, "scan_proxies"), "⚡  प्रॉक्सी स्कैन करें" },
        { (AppLanguage.Hindi, "online"), "ऑनलाइन" },
        { (AppLanguage.Hindi, "offline"), "ऑफ़लाइन" },
        { (AppLanguage.Hindi, "testing_status"), "परीक्षण" },
        { (AppLanguage.Hindi, "latency"), "विलंब" },
        { (AppLanguage.Hindi, "proxy"), "प्रॉक्सी" },
        { (AppLanguage.Hindi, "settings_title"), "सेटिंग्स" },
        { (AppLanguage.Hindi, "theme"), "थीम" },
        { (AppLanguage.Hindi, "dark_mode"), "डार्क" },
        { (AppLanguage.Hindi, "light_mode"), "लाइट" },
        { (AppLanguage.Hindi, "language"), "भाषा" },
        { (AppLanguage.Hindi, "telegram_channel"), "Telegram चैनल" },
        { (AppLanguage.Hindi, "follow_us"), "Telegram पर हमें फ़ॉलो करें" },
        { (AppLanguage.Hindi, "copy"), "कॉपी करें" },
        { (AppLanguage.Hindi, "copied"), "कॉपी हो गया!" },
        { (AppLanguage.Hindi, "save"), "सेव करें" },
        { (AppLanguage.Hindi, "telegram_error"), "Telegram नहीं खुल सका। कृपया सुनिश्चित करें कि Telegram Desktop इंस्टॉल है।\n\n" },
        { (AppLanguage.Hindi, "error_title"), "कनेक्शन त्रुटि" },
        { (AppLanguage.Hindi, "error_app"), "एप्लिकेशन त्रुटि" },
        { (AppLanguage.Hindi, "all_proxies"), "सभी प्रॉक्सी तृतीय पक्षों द्वारा बनाई गई हैं — हम केवल उन्हें एकत्र करते हैं।" },
    };
}
