// Loc.swift — Localized strings, ported verbatim (byte-for-byte identical
// text) from the Windows build's Loc.h, which itself was extracted from the
// Android app's res/values{,-fa,-ru}/strings.xml. Indexed by language code
// ("en","fa","ru").
import Foundation

enum LocKey: String {
    case appName, disclaimer, scanProxies, scanning, settings, language, theme
    case themeSystem, themeLight, themeDark, savedProxies, noSavedProxies
    case tapStarHint, connect, copy, noProxiesFound, systemReady, clearFavorites
    case clearFavConfirmTitle, clearFavConfirmBody, cancel, clear
    case proxySpeedTest, proxySpeedTestDesc, proxyInputHint, paste, startTest
    case testing, testAgain, avgPing, jitter, packetLoss, minMax, quality
    case qualityExcellent, qualityGood, qualityFair, qualityPoor, qualityOffline
    case invalidProxyFormat, supportTitle, supportBanner, cryptoHeader, trxRecommended
    case networkWarning, starHeader, starSubtext, telegramSubtext, thankYou
    case online, offline, forDownloadBadge, russianBadge, back, gitHub, telegramChannel
    case retry, errorLoadTitle
    case autoScanSettingsTitle, autoScanEnableToggle, autoScanIntervalText
    case uploadSpeed, downloadSpeed, fileDownloadEstimator, fileSizeMbHint
    case estimatedTimeResult, estimatedBadge, telegramSpeedDisclaimer
    case offlineNotice, share, bannerSliderToggle
    case stability, save, realTelegramSpeedTitle, dnsLookupLabel, connectionInfo
    case latencyLabel
}

enum Loc {

    static let table: [String: [LocKey: String]] = [
        "en": [
            .latencyLabel: "LATENCY",
            .appName: "Iwana Proxy",
            .disclaimer: "All proxies are created by third parties and we only collect them \u{2713}",
            .scanProxies: "SCAN PROXIES",
            .scanning: "SCANNING...",
            .settings: "Settings",
            .language: "Language",
            .theme: "Appearance",
            .themeSystem: "System",
            .themeLight: "Light",
            .themeDark: "Dark",
            .savedProxies: "Saved Proxies",
            .noSavedProxies: "No saved proxies yet.",
            .tapStarHint: "Tap the bookmark on any proxy to save it here.",
            .connect: "CONNECT",
            .copy: "Copy",
            .share: "Share",
            .offlineNotice: "These proxies were fetched previously and connection to the server failed.",
            .stability: "Stability",
            .save: "Save",
            .realTelegramSpeedTitle: "Real Download Speed on Telegram",
            .dnsLookupLabel: "DNS Lookup",
            .connectionInfo: "Connection Info",
            .bannerSliderToggle: "Promo Banner Slider",
            .noProxiesFound: "No working proxies found.",
            .systemReady: "CONNECTED PROXIES",
            .clearFavorites: "Clear Favorites",
            .clearFavConfirmTitle: "Clear all favorites?",
            .clearFavConfirmBody: "This removes every proxy you saved. This cannot be undone.",
            .cancel: "Cancel",
            .clear: "Clear",
            .proxySpeedTest: "Proxy Speed Test",
            .proxySpeedTestDesc: "Test latency, jitter, and real connection quality of any proxy",
            .proxyInputHint: "Paste tg:// link or server:port:secret",
            .paste: "Paste",
            .startTest: "Start Speed Test",
            .testing: "Testing\u{2026}",
            .testAgain: "Test Again",
            .avgPing: "Avg Ping",
            .jitter: "Jitter",
            .packetLoss: "Packet Loss",
            .minMax: "Min / Max",
            .quality: "Quality",
            .qualityExcellent: "Excellent",
            .qualityGood: "Good",
            .qualityFair: "Fair",
            .qualityPoor: "Poor",
            .qualityOffline: "Offline",
            .invalidProxyFormat: "Please enter a valid proxy address or Telegram proxy link.",
            .supportTitle: "Support Us",
            .supportBanner: "All features of Iwana Proxy are free, always have been, and always will be.",
            .cryptoHeader: "Support with Cryptocurrency",
            .trxRecommended: "TRX (TRON) (Recommended)",
            .networkWarning: "Please ensure you select the exact network specified above when transferring.",
            .starHeader: "Support the Project",
            .starSubtext: "Help the project grow by giving a Star on GitHub:",
            .telegramSubtext: "Follow us on Telegram:",
            .thankYou: "Thank you for supporting Iwana Proxy!",
            .online: "ONLINE", .offline: "OFFLINE",
            .forDownloadBadge: "FOR DOWNLOAD", .russianBadge: "RUSSIAN",
            .back: "Back", .gitHub: "GitHub", .telegramChannel: "Telegram Channel",
            .retry: "Retry", .errorLoadTitle: "Couldn't load proxies",
            .autoScanSettingsTitle: "Auto Scan Settings",
            .autoScanEnableToggle: "Enable Auto Scan",
            .autoScanIntervalText: "Scan Interval: %d seconds",
            .uploadSpeed: "Upload Speed",
            .downloadSpeed: "Download Speed",
            .fileDownloadEstimator: "Download Time Estimator",
            .fileSizeMbHint: "File size (e.g. 74.6 MB)",
            .estimatedTimeResult: "Estimated Time",
            .estimatedBadge: "Estimated",
            .telegramSpeedDisclaimer: "This value is an estimate based on network conditions and is not guaranteed by Telegram.",
        ],
        "fa": [
            .latencyLabel: "تأخیر",
            .appName: "Iwana Proxy",
            .disclaimer: "تمام پروکسی‌ها توسط اشخاص ثالث ایجاد شده‌اند و ما فقط آن‌ها را جمع‌آوری می‌کنیم \u{2713}",
            .scanProxies: "اسکن پروکسی‌ها",
            .scanning: "در حال اسکن...",
            .settings: "تنظیمات",
            .language: "زبان",
            .theme: "ظاهر",
            .themeSystem: "سیستم",
            .themeLight: "روشن",
            .themeDark: "تیره",
            .savedProxies: "پروکسی‌های ذخیره‌شده",
            .noSavedProxies: "هیچ پروکسی ذخیره‌شده‌ای وجود ندارد.",
            .tapStarHint: "روی نشان بوکمارک هر پروکسی بزنید تا اینجا ذخیره شود.",
            .connect: "اتصال",
            .copy: "کپی",
            .share: "اشتراک‌گذاری",
            .offlineNotice: "این پروکسی‌ها قبلاً دریافت شده‌اند و اتصال به سرور با خطا مواجه شد.",
            .stability: "پایداری",
            .save: "ذخیره",
            .realTelegramSpeedTitle: "سرعت واقعی دانلود در تلگرام",
            .dnsLookupLabel: "DNS Lookup",
            .connectionInfo: "اطلاعات اتصال",
            .bannerSliderToggle: "اسلایدر برنامه",
            .noProxiesFound: "پروکسی فعالی یافت نشد.",
            .systemReady: "پروکسی‌های متصل",
            .clearFavorites: "پاک کردن ذخیره‌ها",
            .clearFavConfirmTitle: "همه ذخیره‌ها پاک شود؟",
            .clearFavConfirmBody: "همه پروکسی‌های ذخیره‌شده حذف می‌شوند. این عمل قابل بازگشت نیست.",
            .cancel: "انصراف",
            .clear: "پاک کردن",
            .proxySpeedTest: "تست سرعت پروکسی",
            .proxySpeedTestDesc: "تست دقیق پینگ، جیتر و پایداری اتصال واقعی بر اساس اینترنت شما",
            .proxyInputHint: "لینک tg:// یا server:port:secret را وارد کنید",
            .paste: "جای‌گذاری",
            .startTest: "شروع تست سرعت",
            .testing: "در حال تست\u{2026}",
            .testAgain: "تست مجدد",
            .avgPing: "میانگین پینگ",
            .jitter: "نوسان (جیتر)",
            .packetLoss: "پکت لاس",
            .minMax: "حداقل / حداکثر",
            .quality: "کیفیت اتصال",
            .qualityExcellent: "فوق‌العاده",
            .qualityGood: "خوب",
            .qualityFair: "متوسط",
            .qualityPoor: "ضعیف",
            .qualityOffline: "غیرقابل اتصال",
            .invalidProxyFormat: "لطفاً یک لینک یا آدرس پروکسی معتبر وارد کنید.",
            .supportTitle: "حمایت از ما",
            .supportBanner: "تمام امکانات ایوانا پروکسی رایگان بوده، رایگان هست و رایگان خواهد بود.",
            .cryptoHeader: "حمایت با ارز دیجیتال",
            .trxRecommended: "TRX (TRON) (پیشنهادی)",
            .networkWarning: "لطفاً هنگام انتقال، شبکه را دقیقاً مطابق موارد بالا انتخاب کنید.",
            .starHeader: "حمایت از پروژه",
            .starSubtext: "با دادن یک \u{2066}Star\u{2069} در \u{2066}GitHub\u{2069} به رشد پروژه کمک کنید:",
            .telegramSubtext: "ما را در تلگرام دنبال کنید:",
            .thankYou: "ممنون که از ایوانا پروکسی حمایت میکنید.",
            .online: "متصل", .offline: "قطع",
            .forDownloadBadge: "دانلودی", .russianBadge: "روسی",
            .back: "بازگشت", .gitHub: "گیت‌هاب", .telegramChannel: "کانال تلگرام",
            .retry: "تلاش مجدد", .errorLoadTitle: "دریافت پروکسی‌ها ناموفق بود",
            .autoScanSettingsTitle: "تنظیمات اسکن خودکار",
            .autoScanEnableToggle: "فعال‌سازی اسکن خودکار",
            .autoScanIntervalText: "فاصله اسکن: %d ثانیه",
            .uploadSpeed: "سرعت آپلود",
            .downloadSpeed: "سرعت دانلود",
            .fileDownloadEstimator: "محاسبه زمان دانلود فایل",
            .fileSizeMbHint: "حجم فایل به مگابایت (مثلاً 74.6)",
            .estimatedTimeResult: "زمان تخمینی دانلود",
            .estimatedBadge: "تخمینی",
            .telegramSpeedDisclaimer: "این مقدار تخمینی است و سرعت تضمین شده تلگرام نیست",
        ],
        "ru": [
            .latencyLabel: "ЗАДЕРЖКА",
            .appName: "Iwana Proxy",
            .disclaimer: "Все прокси созданы третьими лицами, мы только собираем их \u{2713}",
            .scanProxies: "СКАНИРОВАТЬ ПРОКСИ",
            .scanning: "СКАНИРОВАНИЕ...",
            .settings: "Настройки",
            .language: "Язык",
            .theme: "Оформление",
            .themeSystem: "Системное",
            .themeLight: "Светлая",
            .themeDark: "Тёмная",
            .savedProxies: "Сохранённые прокси",
            .noSavedProxies: "Нет сохранённых прокси.",
            .tapStarHint: "Нажмите закладку на прокси, чтобы сохранить его здесь.",
            .connect: "ПОДКЛЮЧИТЬСЯ",
            .copy: "Копировать",
            .share: "Поделиться",
            .offlineNotice: "Эти прокси были получены ранее, подключение к серверу не удалось.",
            .stability: "Стабильность",
            .save: "Сохранить",
            .realTelegramSpeedTitle: "Реальная скорость загрузки в Telegram",
            .dnsLookupLabel: "DNS Lookup",
            .connectionInfo: "Информация о соединении",
            .bannerSliderToggle: "Слайдер баннера",
            .noProxiesFound: "Рабочих прокси не найдено.",
            .systemReady: "ПОДКЛЮЧЕННЫЕ ПРОКСИ",
            .clearFavorites: "Очистить избранное",
            .clearFavConfirmTitle: "Очистить всё избранное?",
            .clearFavConfirmBody: "Все сохранённые прокси будут удалены. Это необратимо.",
            .cancel: "Отмена",
            .clear: "Очистить",
            .proxySpeedTest: "Тест скорости прокси",
            .proxySpeedTestDesc: "Реальная проверка пинга, джиттера и качества подключения",
            .proxyInputHint: "Вставьте ссылку tg:// или server:port:secret",
            .paste: "Вставить",
            .startTest: "Начать тест",
            .testing: "Тестирование\u{2026}",
            .testAgain: "Повторить тест",
            .avgPing: "Средний пинг",
            .jitter: "Джиттер",
            .packetLoss: "Потеря пакетов",
            .minMax: "Мин / Макс",
            .quality: "Качество",
            .qualityExcellent: "Отлично",
            .qualityGood: "Хорошо",
            .qualityFair: "Средне",
            .qualityPoor: "Слабо",
            .qualityOffline: "Недоступен",
            .invalidProxyFormat: "Пожалуйста, введите корректный адрес или ссылку прокси.",
            .supportTitle: "Поддержать нас",
            .supportBanner: "Все функции Iwana Proxy были, есть и всегда будут бесплатными.",
            .cryptoHeader: "Поддержка криптовалютой",
            .trxRecommended: "TRX (TRON) (Рекомендуемый)",
            .networkWarning: "Пожалуйста, выбирайте сеть точно в соответствии с указанной выше при переводе.",
            .starHeader: "Поддержка проекта",
            .starSubtext: "Помогите проекту расти, поставив Star на GitHub:",
            .telegramSubtext: "Подписывайтесь на нас в Telegram:",
            .thankYou: "Спасибо за поддержку Iwana Proxy!",
            .online: "ОНЛАЙН", .offline: "ОФЛАЙН",
            .forDownloadBadge: "ДЛЯ СКАЧИВАНИЯ", .russianBadge: "РОССИЯ",
            .back: "Назад", .gitHub: "GitHub", .telegramChannel: "Telegram-канал",
            .retry: "Повторить", .errorLoadTitle: "Не удалось загрузить прокси",
            .autoScanSettingsTitle: "Автосканирование",
            .autoScanEnableToggle: "Включить автосканирование",
            .autoScanIntervalText: "Интервал: %d сек.",
            .uploadSpeed: "Скорость отдачи",
            .downloadSpeed: "Скорость загрузки",
            .fileDownloadEstimator: "Расчет времени скачивания",
            .fileSizeMbHint: "Размер файла в МБ (напр. 74.6)",
            .estimatedTimeResult: "Примерное время",
            .estimatedBadge: "Примерно",
            .telegramSpeedDisclaimer: "Это расчетное значение, скорость Telegram не гарантируется.",
        ],
    ]

    static func t(_ lang: String, _ key: LocKey) -> String {
        let langTable = table[lang] ?? table["en"]!
        return langTable[key] ?? table["en"]![key] ?? ""
    }
}
