// Loc.h — Localized strings extracted verbatim from the Android app's
// res/values{,-fa,-ru}/strings.xml. Indexed by language code ("en","fa","ru").
#pragma once
#include <string>
#include <unordered_map>

namespace Loc {

    enum class Key {
        AppName, Disclaimer, ScanProxies, Scanning, Settings, Language, Theme,
        ThemeSystem, ThemeLight, ThemeDark, SavedProxies, NoSavedProxies,
        TapStarHint, Connect, Copy, NoProxiesFound, SystemReady, ClearFavorites,
        ClearFavConfirmTitle, ClearFavConfirmBody, Cancel, Clear,
        ProxySpeedTest, ProxySpeedTestDesc, ProxyInputHint, Paste, StartTest,
        Testing, TestAgain, AvgPing, Jitter, PacketLoss, MinMax, Quality,
        QualityExcellent, QualityGood, QualityFair, QualityPoor, QualityOffline,
        InvalidProxyFormat, SupportTitle, SupportBanner, CryptoHeader, TrxRecommended,
        NetworkWarning, StarHeader, StarSubtext, TelegramSubtext, ThankYou,
        Online, Offline, ForDownloadBadge, RussianBadge, Back, GitHub, TelegramChannel,
        Retry, ErrorLoadTitle,
        AutoScanSettingsTitle, AutoScanEnableToggle, AutoScanIntervalText,
        UploadSpeed, DownloadSpeed, FileDownloadEstimator, FileSizeMbHint,
        EstimatedTimeResult, EstimatedBadge, TelegramSpeedDisclaimer,
        OfflineNotice, Share, BannerSliderToggle,
        Stability, Save, RealTelegramSpeedTitle, DnsLookupLabel, ConnectionInfo,
    };

    inline const std::unordered_map<std::wstring, std::unordered_map<Key, std::wstring>> Table = {
        { L"en", {
            { Key::AppName, L"Iwana Proxy" },
            { Key::Disclaimer, L"All proxies are created by third parties and we only collect them \u2713" },
            { Key::ScanProxies, L"SCAN PROXIES" },
            { Key::Scanning, L"SCANNING..." },
            { Key::Settings, L"Settings" },
            { Key::Language, L"Language" },
            { Key::Theme, L"Appearance" },
            { Key::ThemeSystem, L"System" },
            { Key::ThemeLight, L"Light" },
            { Key::ThemeDark, L"Dark" },
            { Key::SavedProxies, L"Saved Proxies" },
            { Key::NoSavedProxies, L"No saved proxies yet." },
            { Key::TapStarHint, L"Tap the bookmark on any proxy to save it here." },
            { Key::Connect, L"CONNECT" },
            { Key::Copy, L"Copy" },
            { Key::Share, L"Share" },
            { Key::OfflineNotice, L"These proxies were fetched previously and connection to the server failed." },
            { Key::Stability, L"Stability" },
            { Key::Save, L"Save" },
            { Key::RealTelegramSpeedTitle, L"Real Download Speed on Telegram" },
            { Key::DnsLookupLabel, L"DNS Lookup" },
            { Key::ConnectionInfo, L"Connection Info" },
            { Key::BannerSliderToggle, L"Promo Banner Slider" },
            { Key::NoProxiesFound, L"No working proxies found." },
            { Key::SystemReady, L"CONNECTED PROXIES" },
            { Key::ClearFavorites, L"Clear Favorites" },
            { Key::ClearFavConfirmTitle, L"Clear all favorites?" },
            { Key::ClearFavConfirmBody, L"This removes every proxy you saved. This cannot be undone." },
            { Key::Cancel, L"Cancel" },
            { Key::Clear, L"Clear" },
            { Key::ProxySpeedTest, L"Proxy Speed Test" },
            { Key::ProxySpeedTestDesc, L"Test latency, jitter, and real connection quality of any proxy" },
            { Key::ProxyInputHint, L"Paste tg:// link or server:port:secret" },
            { Key::Paste, L"Paste" },
            { Key::StartTest, L"Start Speed Test" },
            { Key::Testing, L"Testing\u2026" },
            { Key::TestAgain, L"Test Again" },
            { Key::AvgPing, L"Avg Ping" },
            { Key::Jitter, L"Jitter" },
            { Key::PacketLoss, L"Packet Loss" },
            { Key::MinMax, L"Min / Max" },
            { Key::Quality, L"Quality" },
            { Key::QualityExcellent, L"Excellent" },
            { Key::QualityGood, L"Good" },
            { Key::QualityFair, L"Fair" },
            { Key::QualityPoor, L"Poor" },
            { Key::QualityOffline, L"Offline" },
            { Key::InvalidProxyFormat, L"Please enter a valid proxy address or Telegram proxy link." },
            { Key::SupportTitle, L"Support Us" },
            { Key::SupportBanner, L"All features of Iwana Proxy are free, always have been, and always will be." },
            { Key::CryptoHeader, L"Support with Cryptocurrency" },
            { Key::TrxRecommended, L"TRX (TRON) (Recommended)" },
            { Key::NetworkWarning, L"Please ensure you select the exact network specified above when transferring." },
            { Key::StarHeader, L"Support the Project" },
            { Key::StarSubtext, L"Help the project grow by giving a Star on GitHub:" },
            { Key::TelegramSubtext, L"Follow us on Telegram:" },
            { Key::ThankYou, L"Thank you for supporting Iwana Proxy!" },
            { Key::Online, L"ONLINE" }, { Key::Offline, L"OFFLINE" },
            { Key::ForDownloadBadge, L"FOR DOWNLOAD" }, { Key::RussianBadge, L"RUSSIAN" },
            { Key::Back, L"Back" }, { Key::GitHub, L"GitHub" }, { Key::TelegramChannel, L"Telegram Channel" },
            { Key::Retry, L"Retry" }, { Key::ErrorLoadTitle, L"Couldn't load proxies" },
            { Key::AutoScanSettingsTitle, L"Auto Scan Settings" },
            { Key::AutoScanEnableToggle, L"Enable Auto Scan" },
            { Key::AutoScanIntervalText, L"Scan Interval: %d seconds" },
            { Key::UploadSpeed, L"Upload Speed" },
            { Key::DownloadSpeed, L"Download Speed" },
            { Key::FileDownloadEstimator, L"Download Time Estimator" },
            { Key::FileSizeMbHint, L"File size (e.g. 74.6 MB)" },
            { Key::EstimatedTimeResult, L"Estimated Time" },
            { Key::EstimatedBadge, L"Estimated" },
            { Key::TelegramSpeedDisclaimer, L"This value is an estimate based on network conditions and is not guaranteed by Telegram." },
        }},
        { L"fa", {
            { Key::AppName, L"Iwana Proxy" },
            { Key::Disclaimer, L"تمام پروکسی‌ها توسط اشخاص ثالث ایجاد شده‌اند و ما فقط آن‌ها را جمع‌آوری می‌کنیم \u2713" },
            { Key::ScanProxies, L"اسکن پروکسی‌ها" },
            { Key::Scanning, L"در حال اسکن..." },
            { Key::Settings, L"تنظیمات" },
            { Key::Language, L"زبان" },
            { Key::Theme, L"ظاهر" },
            { Key::ThemeSystem, L"سیستم" },
            { Key::ThemeLight, L"روشن" },
            { Key::ThemeDark, L"تیره" },
            { Key::SavedProxies, L"پروکسی‌های ذخیره‌شده" },
            { Key::NoSavedProxies, L"هیچ پروکسی ذخیره‌شده‌ای وجود ندارد." },
            { Key::TapStarHint, L"روی نشان بوکمارک هر پروکسی بزنید تا اینجا ذخیره شود." },
            { Key::Connect, L"اتصال" },
            { Key::Copy, L"کپی" },
            { Key::Share, L"اشتراک‌گذاری" },
            { Key::OfflineNotice, L"این پروکسی‌ها قبلاً دریافت شده‌اند و اتصال به سرور با خطا مواجه شد." },
            { Key::Stability, L"پایداری" },
            { Key::Save, L"ذخیره" },
            { Key::RealTelegramSpeedTitle, L"سرعت واقعی دانلود در تلگرام" },
            { Key::DnsLookupLabel, L"DNS Lookup" },
            { Key::ConnectionInfo, L"اطلاعات اتصال" },
            { Key::BannerSliderToggle, L"اسلایدر برنامه" },
            { Key::NoProxiesFound, L"پروکسی فعالی یافت نشد." },
            { Key::SystemReady, L"پروکسی‌های متصل" },
            { Key::ClearFavorites, L"پاک کردن ذخیره‌ها" },
            { Key::ClearFavConfirmTitle, L"همه ذخیره‌ها پاک شود؟" },
            { Key::ClearFavConfirmBody, L"همه پروکسی‌های ذخیره‌شده حذف می‌شوند. این عمل قابل بازگشت نیست." },
            { Key::Cancel, L"انصراف" },
            { Key::Clear, L"پاک کردن" },
            { Key::ProxySpeedTest, L"تست سرعت پروکسی" },
            { Key::ProxySpeedTestDesc, L"تست دقیق پینگ، جیتر و پایداری اتصال واقعی بر اساس اینترنت شما" },
            { Key::ProxyInputHint, L"لینک tg:// یا server:port:secret را وارد کنید" },
            { Key::Paste, L"جای‌گذاری" },
            { Key::StartTest, L"شروع تست سرعت" },
            { Key::Testing, L"در حال تست\u2026" },
            { Key::TestAgain, L"تست مجدد" },
            { Key::AvgPing, L"میانگین پینگ" },
            { Key::Jitter, L"نوسان (جیتر)" },
            { Key::PacketLoss, L"پکت لاس" },
            { Key::MinMax, L"حداقل / حداکثر" },
            { Key::Quality, L"کیفیت اتصال" },
            { Key::QualityExcellent, L"فوق‌العاده" },
            { Key::QualityGood, L"خوب" },
            { Key::QualityFair, L"متوسط" },
            { Key::QualityPoor, L"ضعیف" },
            { Key::QualityOffline, L"غیرقابل اتصال" },
            { Key::InvalidProxyFormat, L"لطفاً یک لینک یا آدرس پروکسی معتبر وارد کنید." },
            { Key::SupportTitle, L"حمایت از ما" },
            { Key::SupportBanner, L"تمام امکانات ایوانا پروکسی رایگان بوده، رایگان هست و رایگان خواهد بود." },
            { Key::CryptoHeader, L"حمایت با ارز دیجیتال" },
            { Key::TrxRecommended, L"TRX (TRON) (پیشنهادی)" },
            { Key::NetworkWarning, L"لطفاً هنگام انتقال، شبکه را دقیقاً مطابق موارد بالا انتخاب کنید." },
            { Key::StarHeader, L"حمایت از پروژه" },
            { Key::StarSubtext, L"با دادن یک \u2066Star\u2069 در \u2066GitHub\u2069 به رشد پروژه کمک کنید:" },
            { Key::TelegramSubtext, L"ما را در تلگرام دنبال کنید:" },
            { Key::ThankYou, L"ممنون که از ایوانا پروکسی حمایت میکنید." },
            { Key::Online, L"متصل" }, { Key::Offline, L"قطع" },
            { Key::ForDownloadBadge, L"دانلودی" }, { Key::RussianBadge, L"روسی" },
            { Key::Back, L"بازگشت" }, { Key::GitHub, L"گیت‌هاب" }, { Key::TelegramChannel, L"کانال تلگرام" },
            { Key::Retry, L"تلاش مجدد" }, { Key::ErrorLoadTitle, L"دریافت پروکسی‌ها ناموفق بود" },
            { Key::AutoScanSettingsTitle, L"تنظیمات اسکن خودکار" },
            { Key::AutoScanEnableToggle, L"فعال‌سازی اسکن خودکار" },
            { Key::AutoScanIntervalText, L"فاصله اسکن: %d ثانیه" },
            { Key::UploadSpeed, L"سرعت آپلود" },
            { Key::DownloadSpeed, L"سرعت دانلود" },
            { Key::FileDownloadEstimator, L"محاسبه زمان دانلود فایل" },
            { Key::FileSizeMbHint, L"حجم فایل به مگابایت (مثلاً 74.6)" },
            { Key::EstimatedTimeResult, L"زمان تخمینی دانلود" },
            { Key::EstimatedBadge, L"تخمینی" },
            { Key::TelegramSpeedDisclaimer, L"این مقدار تخمینی است و سرعت تضمین شده تلگرام نیست" },
        }},
        { L"ru", {
            { Key::AppName, L"Iwana Proxy" },
            { Key::Disclaimer, L"Все прокси созданы третьими лицами, мы только собираем их \u2713" },
            { Key::ScanProxies, L"СКАНИРОВАТЬ ПРОКСИ" },
            { Key::Scanning, L"СКАНИРОВАНИЕ..." },
            { Key::Settings, L"Настройки" },
            { Key::Language, L"Язык" },
            { Key::Theme, L"Оформление" },
            { Key::ThemeSystem, L"Системное" },
            { Key::ThemeLight, L"Светлая" },
            { Key::ThemeDark, L"Тёмная" },
            { Key::SavedProxies, L"Сохранённые прокси" },
            { Key::NoSavedProxies, L"Нет сохранённых прокси." },
            { Key::TapStarHint, L"Нажмите закладку на прокси, чтобы сохранить его здесь." },
            { Key::Connect, L"ПОДКЛЮЧИТЬСЯ" },
            { Key::Copy, L"Копировать" },
            { Key::Share, L"Поделиться" },
            { Key::OfflineNotice, L"Эти прокси были получены ранее, подключение к серверу не удалось." },
            { Key::Stability, L"Стабильность" },
            { Key::Save, L"Сохранить" },
            { Key::RealTelegramSpeedTitle, L"Реальная скорость загрузки в Telegram" },
            { Key::DnsLookupLabel, L"DNS Lookup" },
            { Key::ConnectionInfo, L"Информация о соединении" },
            { Key::BannerSliderToggle, L"Слайдер баннера" },
            { Key::NoProxiesFound, L"Рабочих прокси не найдено." },
            { Key::SystemReady, L"ПОДКЛЮЧЕННЫЕ ПРОКСИ" },
            { Key::ClearFavorites, L"Очистить избранное" },
            { Key::ClearFavConfirmTitle, L"Очистить всё избранное?" },
            { Key::ClearFavConfirmBody, L"Все сохранённые прокси будут удалены. Это необратимо." },
            { Key::Cancel, L"Отмена" },
            { Key::Clear, L"Очистить" },
            { Key::ProxySpeedTest, L"Тест скорости прокси" },
            { Key::ProxySpeedTestDesc, L"Реальная проверка пинга, джиттера и качества подключения" },
            { Key::ProxyInputHint, L"Вставьте ссылку tg:// или server:port:secret" },
            { Key::Paste, L"Вставить" },
            { Key::StartTest, L"Начать тест" },
            { Key::Testing, L"Тестирование\u2026" },
            { Key::TestAgain, L"Повторить тест" },
            { Key::AvgPing, L"Средний пинг" },
            { Key::Jitter, L"Джиттер" },
            { Key::PacketLoss, L"Потеря пакетов" },
            { Key::MinMax, L"Мин / Макс" },
            { Key::Quality, L"Качество" },
            { Key::QualityExcellent, L"Отлично" },
            { Key::QualityGood, L"Хорошо" },
            { Key::QualityFair, L"Средне" },
            { Key::QualityPoor, L"Слабо" },
            { Key::QualityOffline, L"Недоступен" },
            { Key::InvalidProxyFormat, L"Пожалуйста, введите корректный адрес или ссылку прокси." },
            { Key::SupportTitle, L"Поддержать нас" },
            { Key::SupportBanner, L"Все функции Iwana Proxy были, есть и всегда будут бесплатными." },
            { Key::CryptoHeader, L"Поддержка криптовалютой" },
            { Key::TrxRecommended, L"TRX (TRON) (Рекомендуемый)" },
            { Key::NetworkWarning, L"Пожалуйста, выбирайте сеть точно в соответствии с указанной выше при переводе." },
            { Key::StarHeader, L"Поддержка проекта" },
            { Key::StarSubtext, L"Помогите проекту расти, поставив Star на GitHub:" },
            { Key::TelegramSubtext, L"Подписывайтесь на нас в Telegram:" },
            { Key::ThankYou, L"Спасибо за поддержку Iwana Proxy!" },
            { Key::Online, L"ОНЛАЙН" }, { Key::Offline, L"ОФЛАЙН" },
            { Key::ForDownloadBadge, L"ДЛЯ СКАЧИВАНИЯ" }, { Key::RussianBadge, L"РОССИЯ" },
            { Key::Back, L"Назад" }, { Key::GitHub, L"GitHub" }, { Key::TelegramChannel, L"Telegram-канал" },
            { Key::Retry, L"Повторить" }, { Key::ErrorLoadTitle, L"Не удалось загрузить прокси" },
            { Key::AutoScanSettingsTitle, L"Автосканирование" },
            { Key::AutoScanEnableToggle, L"Включить автосканирование" },
            { Key::AutoScanIntervalText, L"Интервал: %d сек." },
            { Key::UploadSpeed, L"Скорость отдачи" },
            { Key::DownloadSpeed, L"Скорость загрузки" },
            { Key::FileDownloadEstimator, L"Расчет времени скачивания" },
            { Key::FileSizeMbHint, L"Размер файла в МБ (напр. 74.6)" },
            { Key::EstimatedTimeResult, L"Примерное время" },
            { Key::EstimatedBadge, L"Примерно" },
            { Key::TelegramSpeedDisclaimer, L"Это расчетное значение, скорость Telegram не гарантируется." },
        }},
    };

    inline std::wstring T(const std::wstring& lang, Key key) {
        auto langIt = Table.find(lang);
        if (langIt == Table.end()) langIt = Table.find(L"en");
        auto it = langIt->second.find(key);
        if (it != langIt->second.end()) return it->second;
        return Table.at(L"en").at(key);
    }

}
