// Loc.h — Localized strings (fa/en/ru), ported verbatim (same key set and
// translated text) from the Windows build's Loc.h.
// Uses UTF-8 std::string throughout (Pango/GTK are UTF-8 native, unlike
// GDI+ which needed UTF-16 std::wstring on Windows). Indexed by language
// code ("en","fa","ru").
#pragma once
#include <string>
#include <unordered_map>

namespace Loc {

    enum class Key {
        AppName, Disclaimer, ScanProxies, Scanning, Settings, Language, Theme,
        ThemeSystem, ThemeLight, ThemeDark, SavedProxies, NoSavedProxies,
        TapStarHint, Connect, Copy, NoProxiesFound, SystemReady, ClearFavorites,
        ClearFavConfirmTitle, ClearFavConfirmBody, Cancel, Clear,
        ProxySpeedTest, ProxySpeedTestDesc, ProxyInputHint, Paste, StartTest,
        Testing, TestAgain, AvgPing, Jitter, PacketLoss, MinMax, Quality,
        QualityExcellent, QualityGood, QualityFair, QualityPoor, QualityOffline,
        InvalidProxyFormat, SupportTitle, SupportBanner, CryptoHeader, TrxRecommended,
        NetworkWarning, StarHeader, StarSubtext, TelegramSubtext, ThankYou,
        Online, Offline, ForDownloadBadge, RussianBadge, LatencyLabel, Back, GitHub, TelegramChannel,
        Retry, ErrorLoadTitle,
        AutoScanSettingsTitle, AutoScanEnableToggle, AutoScanIntervalText,
        UploadSpeed, DownloadSpeed, FileDownloadEstimator, FileSizeMbHint,
        EstimatedTimeResult, EstimatedBadge, TelegramSpeedDisclaimer,
        OfflineNotice, Share, BannerSliderToggle,
        Stability, Save, RealTelegramSpeedTitle, DnsLookupLabel, ConnectionInfo,
    };

    inline const std::unordered_map<std::string, std::unordered_map<Key, std::string>> Table = {
        { "en", {
            { Key::AppName, "Iwana Proxy" },
            { Key::Disclaimer, "All proxies are created by third parties and we only collect them \u2713" },
            { Key::ScanProxies, "SCAN PROXIES" },
            { Key::Scanning, "SCANNING..." },
            { Key::Settings, "Settings" },
            { Key::Language, "Language" },
            { Key::Theme, "Appearance" },
            { Key::ThemeSystem, "System" },
            { Key::ThemeLight, "Light" },
            { Key::ThemeDark, "Dark" },
            { Key::SavedProxies, "Saved Proxies" },
            { Key::NoSavedProxies, "No saved proxies yet." },
            { Key::TapStarHint, "Tap the bookmark on any proxy to save it here." },
            { Key::Connect, "CONNECT" },
            { Key::Copy, "Copy" },
            { Key::Share, "Share" },
            { Key::OfflineNotice, "These proxies were fetched previously and connection to the server failed." },
            { Key::Stability, "Stability" },
            { Key::Save, "Save" },
            { Key::RealTelegramSpeedTitle, "Real Download Speed on Telegram" },
            { Key::DnsLookupLabel, "DNS Lookup" },
            { Key::ConnectionInfo, "Connection Info" },
            { Key::BannerSliderToggle, "Promo Banner Slider" },
            { Key::NoProxiesFound, "No working proxies found." },
            { Key::SystemReady, "CONNECTED PROXIES" },
            { Key::ClearFavorites, "Clear Favorites" },
            { Key::ClearFavConfirmTitle, "Clear all favorites?" },
            { Key::ClearFavConfirmBody, "This removes every proxy you saved. This cannot be undone." },
            { Key::Cancel, "Cancel" },
            { Key::Clear, "Clear" },
            { Key::ProxySpeedTest, "Proxy Speed Test" },
            { Key::ProxySpeedTestDesc, "Test latency, jitter, and real connection quality of any proxy" },
            { Key::ProxyInputHint, "Paste tg:// link or server:port:secret" },
            { Key::Paste, "Paste" },
            { Key::StartTest, "Start Speed Test" },
            { Key::Testing, "Testing\u2026" },
            { Key::TestAgain, "Test Again" },
            { Key::AvgPing, "Avg Ping" },
            { Key::Jitter, "Jitter" },
            { Key::PacketLoss, "Packet Loss" },
            { Key::MinMax, "Min / Max" },
            { Key::Quality, "Quality" },
            { Key::QualityExcellent, "Excellent" },
            { Key::QualityGood, "Good" },
            { Key::QualityFair, "Fair" },
            { Key::QualityPoor, "Poor" },
            { Key::QualityOffline, "Offline" },
            { Key::InvalidProxyFormat, "Please enter a valid proxy address or Telegram proxy link." },
            { Key::SupportTitle, "Support Us" },
            { Key::SupportBanner, "All features of Iwana Proxy are free, always have been, and always will be." },
            { Key::CryptoHeader, "Support with Cryptocurrency" },
            { Key::TrxRecommended, "TRX (TRON) (Recommended)" },
            { Key::NetworkWarning, "Please ensure you select the exact network specified above when transferring." },
            { Key::StarHeader, "Support the Project" },
            { Key::StarSubtext, "Help the project grow by giving a Star on GitHub:" },
            { Key::TelegramSubtext, "Follow us on Telegram:" },
            { Key::ThankYou, "Thank you for supporting Iwana Proxy!" },
            { Key::Online, "ONLINE" }, { Key::Offline, "OFFLINE" }, { Key::LatencyLabel, "LATENCY" },
            { Key::ForDownloadBadge, "FOR DOWNLOAD" }, { Key::RussianBadge, "RUSSIAN" },
            { Key::Back, "Back" }, { Key::GitHub, "GitHub" }, { Key::TelegramChannel, "Telegram Channel" },
            { Key::Retry, "Retry" }, { Key::ErrorLoadTitle, "Couldn't load proxies" },
            { Key::AutoScanSettingsTitle, "Auto Scan Settings" },
            { Key::AutoScanEnableToggle, "Enable Auto Scan" },
            { Key::AutoScanIntervalText, "Scan Interval: %d seconds" },
            { Key::UploadSpeed, "Upload Speed" },
            { Key::DownloadSpeed, "Download Speed" },
            { Key::FileDownloadEstimator, "Download Time Estimator" },
            { Key::FileSizeMbHint, "File size (e.g. 74.6 MB)" },
            { Key::EstimatedTimeResult, "Estimated Time" },
            { Key::EstimatedBadge, "Estimated" },
            { Key::TelegramSpeedDisclaimer, "This value is an estimate based on network conditions and is not guaranteed by Telegram." },
        }},
        { "fa", {
            { Key::AppName, "Iwana Proxy" },
            { Key::Disclaimer, "تمام پروکسی‌ها توسط اشخاص ثالث ایجاد شده‌اند و ما فقط آن‌ها را جمع‌آوری می‌کنیم \u2713" },
            { Key::ScanProxies, "اسکن پروکسی‌ها" },
            { Key::Scanning, "در حال اسکن..." },
            { Key::Settings, "تنظیمات" },
            { Key::Language, "زبان" },
            { Key::Theme, "ظاهر" },
            { Key::ThemeSystem, "سیستم" },
            { Key::ThemeLight, "روشن" },
            { Key::ThemeDark, "تیره" },
            { Key::SavedProxies, "پروکسی‌های ذخیره‌شده" },
            { Key::NoSavedProxies, "هیچ پروکسی ذخیره‌شده‌ای وجود ندارد." },
            { Key::TapStarHint, "روی نشان بوکمارک هر پروکسی بزنید تا اینجا ذخیره شود." },
            { Key::Connect, "اتصال" },
            { Key::Copy, "کپی" },
            { Key::Share, "اشتراک‌گذاری" },
            { Key::OfflineNotice, "این پروکسی‌ها قبلاً دریافت شده‌اند و اتصال به سرور با خطا مواجه شد." },
            { Key::Stability, "پایداری" },
            { Key::Save, "ذخیره" },
            { Key::RealTelegramSpeedTitle, "سرعت واقعی دانلود در تلگرام" },
            { Key::DnsLookupLabel, "DNS Lookup" },
            { Key::ConnectionInfo, "اطلاعات اتصال" },
            { Key::BannerSliderToggle, "اسلایدر برنامه" },
            { Key::NoProxiesFound, "پروکسی فعالی یافت نشد." },
            { Key::SystemReady, "پروکسی‌های متصل" },
            { Key::ClearFavorites, "پاک کردن ذخیره‌ها" },
            { Key::ClearFavConfirmTitle, "همه ذخیره‌ها پاک شود؟" },
            { Key::ClearFavConfirmBody, "همه پروکسی‌های ذخیره‌شده حذف می‌شوند. این عمل قابل بازگشت نیست." },
            { Key::Cancel, "انصراف" },
            { Key::Clear, "پاک کردن" },
            { Key::ProxySpeedTest, "تست سرعت پروکسی" },
            { Key::ProxySpeedTestDesc, "تست دقیق پینگ، جیتر و پایداری اتصال واقعی بر اساس اینترنت شما" },
            { Key::ProxyInputHint, "لینک tg:// یا server:port:secret را وارد کنید" },
            { Key::Paste, "جای‌گذاری" },
            { Key::StartTest, "شروع تست سرعت" },
            { Key::Testing, "در حال تست\u2026" },
            { Key::TestAgain, "تست مجدد" },
            { Key::AvgPing, "میانگین پینگ" },
            { Key::Jitter, "نوسان (جیتر)" },
            { Key::PacketLoss, "پکت لاس" },
            { Key::MinMax, "حداقل / حداکثر" },
            { Key::Quality, "کیفیت اتصال" },
            { Key::QualityExcellent, "فوق‌العاده" },
            { Key::QualityGood, "خوب" },
            { Key::QualityFair, "متوسط" },
            { Key::QualityPoor, "ضعیف" },
            { Key::QualityOffline, "غیرقابل اتصال" },
            { Key::InvalidProxyFormat, "لطفاً یک لینک یا آدرس پروکسی معتبر وارد کنید." },
            { Key::SupportTitle, "حمایت از ما" },
            { Key::SupportBanner, "تمام امکانات ایوانا پروکسی رایگان بوده، رایگان هست و رایگان خواهد بود." },
            { Key::CryptoHeader, "حمایت با ارز دیجیتال" },
            { Key::TrxRecommended, "TRX (TRON) (پیشنهادی)" },
            { Key::NetworkWarning, "لطفاً هنگام انتقال، شبکه را دقیقاً مطابق موارد بالا انتخاب کنید." },
            { Key::StarHeader, "حمایت از پروژه" },
            { Key::StarSubtext, "با دادن یک \u2066Star\u2069 در \u2066GitHub\u2069 به رشد پروژه کمک کنید:" },
            { Key::TelegramSubtext, "ما را در تلگرام دنبال کنید:" },
            { Key::ThankYou, "ممنون که از ایوانا پروکسی حمایت میکنید." },
            { Key::Online, "متصل" }, { Key::Offline, "قطع" }, { Key::LatencyLabel, "تاخیر" },
            { Key::ForDownloadBadge, "دانلودی" }, { Key::RussianBadge, "روسی" },
            { Key::Back, "بازگشت" }, { Key::GitHub, "گیت‌هاب" }, { Key::TelegramChannel, "کانال تلگرام" },
            { Key::Retry, "تلاش مجدد" }, { Key::ErrorLoadTitle, "دریافت پروکسی‌ها ناموفق بود" },
            { Key::AutoScanSettingsTitle, "تنظیمات اسکن خودکار" },
            { Key::AutoScanEnableToggle, "فعال‌سازی اسکن خودکار" },
            { Key::AutoScanIntervalText, "فاصله اسکن: %d ثانیه" },
            { Key::UploadSpeed, "سرعت آپلود" },
            { Key::DownloadSpeed, "سرعت دانلود" },
            { Key::FileDownloadEstimator, "محاسبه زمان دانلود فایل" },
            { Key::FileSizeMbHint, "حجم فایل به مگابایت (مثلاً 74.6)" },
            { Key::EstimatedTimeResult, "زمان تخمینی دانلود" },
            { Key::EstimatedBadge, "تخمینی" },
            { Key::TelegramSpeedDisclaimer, "این مقدار تخمینی است و سرعت تضمین شده تلگرام نیست" },
        }},
        { "ru", {
            { Key::AppName, "Iwana Proxy" },
            { Key::Disclaimer, "Все прокси созданы третьими лицами, мы только собираем их \u2713" },
            { Key::ScanProxies, "СКАНИРОВАТЬ ПРОКСИ" },
            { Key::Scanning, "СКАНИРОВАНИЕ..." },
            { Key::Settings, "Настройки" },
            { Key::Language, "Язык" },
            { Key::Theme, "Оформление" },
            { Key::ThemeSystem, "Системное" },
            { Key::ThemeLight, "Светлая" },
            { Key::ThemeDark, "Тёмная" },
            { Key::SavedProxies, "Сохранённые прокси" },
            { Key::NoSavedProxies, "Нет сохранённых прокси." },
            { Key::TapStarHint, "Нажмите закладку на прокси, чтобы сохранить его здесь." },
            { Key::Connect, "ПОДКЛЮЧИТЬСЯ" },
            { Key::Copy, "Копировать" },
            { Key::Share, "Поделиться" },
            { Key::OfflineNotice, "Эти прокси были получены ранее, подключение к серверу не удалось." },
            { Key::Stability, "Стабильность" },
            { Key::Save, "Сохранить" },
            { Key::RealTelegramSpeedTitle, "Реальная скорость загрузки в Telegram" },
            { Key::DnsLookupLabel, "DNS Lookup" },
            { Key::ConnectionInfo, "Информация о соединении" },
            { Key::BannerSliderToggle, "Слайдер баннера" },
            { Key::NoProxiesFound, "Рабочих прокси не найдено." },
            { Key::SystemReady, "ПОДКЛЮЧЕННЫЕ ПРОКСИ" },
            { Key::ClearFavorites, "Очистить избранное" },
            { Key::ClearFavConfirmTitle, "Очистить всё избранное?" },
            { Key::ClearFavConfirmBody, "Все сохранённые прокси будут удалены. Это необратимо." },
            { Key::Cancel, "Отмена" },
            { Key::Clear, "Очистить" },
            { Key::ProxySpeedTest, "Тест скорости прокси" },
            { Key::ProxySpeedTestDesc, "Реальная проверка пинга, джиттера и качества подключения" },
            { Key::ProxyInputHint, "Вставьте ссылку tg:// или server:port:secret" },
            { Key::Paste, "Вставить" },
            { Key::StartTest, "Начать тест" },
            { Key::Testing, "Тестирование\u2026" },
            { Key::TestAgain, "Повторить тест" },
            { Key::AvgPing, "Средний пинг" },
            { Key::Jitter, "Джиттер" },
            { Key::PacketLoss, "Потеря пакетов" },
            { Key::MinMax, "Мин / Макс" },
            { Key::Quality, "Качество" },
            { Key::QualityExcellent, "Отлично" },
            { Key::QualityGood, "Хорошо" },
            { Key::QualityFair, "Средне" },
            { Key::QualityPoor, "Слабо" },
            { Key::QualityOffline, "Недоступен" },
            { Key::InvalidProxyFormat, "Пожалуйста, введите корректный адрес или ссылку прокси." },
            { Key::SupportTitle, "Поддержать нас" },
            { Key::SupportBanner, "Все функции Iwana Proxy были, есть и всегда будут бесплатными." },
            { Key::CryptoHeader, "Поддержка криптовалютой" },
            { Key::TrxRecommended, "TRX (TRON) (Рекомендуемый)" },
            { Key::NetworkWarning, "Пожалуйста, выбирайте сеть точно в соответствии с указанной выше при переводе." },
            { Key::StarHeader, "Поддержка проекта" },
            { Key::StarSubtext, "Помогите проекту расти, поставив Star на GitHub:" },
            { Key::TelegramSubtext, "Подписывайтесь на нас в Telegram:" },
            { Key::ThankYou, "Спасибо за поддержку Iwana Proxy!" },
            { Key::Online, "ОНЛАЙН" }, { Key::Offline, "ОФЛАЙН" }, { Key::LatencyLabel, "ЗАДЕРЖКА" },
            { Key::ForDownloadBadge, "ДЛЯ СКАЧИВАНИЯ" }, { Key::RussianBadge, "РОССИЯ" },
            { Key::Back, "Назад" }, { Key::GitHub, "GitHub" }, { Key::TelegramChannel, "Telegram-канал" },
            { Key::Retry, "Повторить" }, { Key::ErrorLoadTitle, "Не удалось загрузить прокси" },
            { Key::AutoScanSettingsTitle, "Автосканирование" },
            { Key::AutoScanEnableToggle, "Включить автосканирование" },
            { Key::AutoScanIntervalText, "Интервал: %d сек." },
            { Key::UploadSpeed, "Скорость отдачи" },
            { Key::DownloadSpeed, "Скорость загрузки" },
            { Key::FileDownloadEstimator, "Расчет времени скачивания" },
            { Key::FileSizeMbHint, "Размер файла в МБ (напр. 74.6)" },
            { Key::EstimatedTimeResult, "Примерное время" },
            { Key::EstimatedBadge, "Примерно" },
            { Key::TelegramSpeedDisclaimer, "Это расчетное значение, скорость Telegram не гарантируется." },
        }},
    };

    inline std::string T(const std::string& lang, Key key) {
        auto langIt = Table.find(lang);
        if (langIt == Table.end()) langIt = Table.find("en");
        auto it = langIt->second.find(key);
        if (it != langIt->second.end()) return it->second;
        return Table.at("en").at(key);
    }

}
